### ISSUE TITLE
Record and Equality of JObject (Json.NET)

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#247]
Is there a way to let two objects of type MyClass : Record<MyClass> be equal if MyClass has a property of type JObject?

[OptOutOfEq] ignores this property but I want to compare content.

Could be done with JObject.DeepEquals or comparing the keyvalue pairs (JObject is IList and IDictionary).

Is there an option to specify a comparer function? Or is it useful for Record<A> in general to compare by some interface?

**Comment by louthy** [comment]
I will be adding a feature that will allow you to specify your own `Eq<JObject>` implementation.  But that's not there yet.  The best short term option you have is to use `[OptOutOfEq]` on the field/property and then override the `Equals` yourself:

```c#
    public override bool Equals(MyClass rhs) =>
        base.Equals(rhs) && JObject.DeepEquals(this.Property, rhs.Property);
```
You'll need to do a similar thing for `Equals(object rhs)` and `operator==` (and the comparison operators if you want ordering).

**Comment by StefanBertels** [comment]
Nice, will completely solve my use case.

Do you think this should / could be added for comparison, too?

This would be not as easy for `JObject` because there is no comparer equivalent to JObject.DeepEquals AFAIK. (And I personally don't need comparison.) Just for completeness...

**Comment by louthy** [comment]
@StefanBertels  

I would only implement what you can, and opt-out of what doesn't make sense in the comparison.

By the way, you should take a look at the new release, because you don't need to provide your own Equals overrides now.

https://github.com/louthy/language-ext/releases/tag/v2.1.14

**Comment by StefanBertels** [comment]
I'm not getting the desired result with `EqJObject : Eq<JObject>` in my project targetting `netstandard2.0`.

Seems equality operator does not use EqJObject.Equals.

I read about `ClassInstancesAssembly.Register` in https://github.com/louthy/language-ext/releases/tag/v2.1.14 -- is this necessary with .NET Standard 2.0?

My project file
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net462</TargetFrameworks>
    <RuntimeIdentifiers>win10-x64;win-x64;win</RuntimeIdentifiers>
    <RootNamespace>MyProject</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LanguageExt.core" Version="2.1.18" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="xunit" Version="2.3.0-beta4-build3742" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta4-build3742" />
  </ItemGroup>

</Project>
```
I want to use `netstandard2.0`. I added `net462` so that test runners can run my xunit test (included in project). At least `dotnet xunit` and NCrunch work now (by running tests for net462).

But the test fails.

If I add `ClassInstancesAssembly.Register(typeof(EqJObject).GetTypeInfo().Assembly);` build fails: `Register` seems to be defined in `netstandard2.0` but not in `net462`.

**Comment by louthy** [comment]
>  is this necessary with .NET Standard 2.0?

Yes, as the lang-ext builds netstandard 1.3, not 2.0, so the features of assembly discovery are not available.

> If I add ClassInstancesAssembly.Register(typeof(EqJObject).GetTypeInfo().Assembly); build fails: Register seems to be defined in netstandard2.0 but not in net462.

You will need to use a `#if` condition for your framework.  I will probably allow Register to exist as an empty function so this isn't necessary in the future, but a bit swamped right now, so don't have much time to do a new build

**Comment by StefanBertels** [comment]
Ok, it will compile with
```
#if COREFX
            ClassInstancesAssembly.Register(typeof(EqJObject).GetTypeInfo().Assembly);
#endif
```
But that does not help because test is running on `net462`..

**Comment by StefanBertels** [comment]
Note: I removed target netstandard2.0 and for now just go with net461 in one project. 

But EqJObject (your suggested solution for 2.1.14+) does not work (for me):

```
public struct EqJObject : Eq<JObject> // without namespace
{
    public bool Equals(JObject x, JObject y) =>
        JObject.DeepEquals(x, y);

    public int GetHashCode(JObject x) =>
        x.GetHashCode();
}
```

My test:
```
        public class MyClass2 : Record<MyClass2>
        {
            public JObject Json { get; set; }
        }


        [Fact]
        private void TestEqual()
        {
            Assert.Equal(new MyClass2
            {
                Json = new JObject(),
            }, new MyClass2
            {
                Json = new JObject(),
            });
        }

```
This test is fails. What's going wrong?

I use LanguageExt.Core 2.1.21 and Xunit 2.2.0.


Side node: 
```
            Assert.Equal(new JObject(), new JObject());  // success because Xunit has some permissive logic, trying to compare by using IDictionary, IEnumerable interfaces etc.
            Assert.True(new JObject() == new JObject()); // fails
            Assert.True(new JObject().Equals(new JObject())); // fails
```

**Comment by louthy** [comment]
Hi Stefan, I'll try and get a look at this next week.  Very time poor at the moment, sorry.

**Comment by louthy** [comment]
Bit slow on the fix, but this should work now in `v2.2.15-beta`

**Comment by StefanBertels** [comment]
Hmm. Just pasted my code above into a small console app (net462) with LanguageExt 2.2.27-beta and my test still fails. Looks like methods GetHashCode and Equals of EqJObject don't get called when running my test.
