### ISSUE TITLE
Stack overflow error after using Sequence to get from IEnumerable<Option<T>> to Option<IEnumerable<T>>

### ISSUE THREAD

**Issue by kalderman** [louthy/language-ext#533]
I have some code sorta like this:

```
var someData = Enumerable
    .Range(0, 30000)
    .Select(_ => Guid.NewGuid().ToString())
    .ToArray();

var result = someData
    .Select(Some)
    .Sequence()
    .Map(x => x.ToArray());
```

This code is simplified a bit but the operations are approximately the same.
`someData` is a reasonable approximation of my data; there's also a function that executes some business logic where `Some` is but it is not needed to reproduce the problem.

The stack overflow happens on the call to ToArray. 

The code above should produce the stack overflow, if not increase the range and/or the size of the strings.

**Comment by louthy** [comment]
Fixed in `3.1.14`

**Comment by kalderman** [comment]
Thanks for the quick turn around.  However, this is still broken when targeting .NET framework 4.5+.
This may be a problem inherent in .NET framework.
You can see the test fail (among others) by adding the net461 target to the test project.
[Which is already a pull request](https://github.com/louthy/language-ext/pull/531/commits/e6399e10bc5e2ce455b8fd9a934670bd120e5b3f)

**Comment by colethecoder** [comment]
It looks like .Net Framework is doing the same as the LangExt code was doing:

```csharp
        public static IEnumerable<TSource> Concat<TSource>(this IEnumerable<TSource> first, IEnumerable<TSource> second) {
            if (first == null) throw Error.ArgumentNull("first");
            if (second == null) throw Error.ArgumentNull("second");
            return ConcatIterator<TSource>(first, second);
        }

        static IEnumerable<TSource> ConcatIterator<TSource>(IEnumerable<TSource> first, IEnumerable<TSource> second) {
            foreach (TSource element in first) yield return element;
            foreach (TSource element in second) yield return element;
        }
```

https://github.com/Microsoft/referencesource/blob/60a4f8b853f60a424e36c7bf60f9b5b5f1973ed1/System.Core/System/Linq/Enumerable.cs#L800

.Net Core has a load of optimisations:

https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Concat.cs

**Comment by louthy** [comment]
I have committed a fix for this that will be in the next release.
